### ISSUE TITLE
[CHORE] Upgrade GitVersion to version 6

### ISSUE THREAD

**Issue by guibranco** [guibranco/github-infisical-secrets-check-action#51]
This chore updates the GitVersion tool from version 5 to version 6, addressing breaking changes and configuration updates. The changes will ensure compatibility with the latest GitVersion release.

### Tasks  
1. **Update CI Pipeline File**  
   - Locate the pipeline file (`deploy.yml`, `ci.yml`, or `build.yml`) in the `.github/workflows` directory.  
   - Identify the step installing GitVersion (likely resembling the following):  
     ```yml
     - name: Install GitVersion 
       uses: gittools/actions/gitversion/setup@v2
       with:
         versionSpec: '5.x'
     ```  
   - Update it to use version 6:  
     ```yml
     - name: Install GitVersion 
       uses: gittools/actions/gitversion/setup@v3
       with:
         versionSpec: '6.x'
     ```  

2. **Update GitVersion.yml Configuration**  
   - Replace the deprecated `mode: mainline` with:  
     ```yaml
     workflow: GitHubFlow/v1
     mode: ContinuousDeployment
     ```  
   - Ensure the updated configuration complies with version 6 syntax.

### References  
- [GitVersion GitHubFlow Examples](https://gitversion.net/docs/learn/branching-strategies/githubflow/examples)
- [Breaking Changes in GitVersion 6](https://github.com/GitTools/GitVersion/blob/main/BREAKING_CHANGES.md)

### Acceptance Criteria  
- CI pipeline successfully uses version 3 of the [gittools/actions/gitversion/setup](https://github.com/GitTools/actions)
- CI pipeline successfully installs and uses GitVersion version 6.  
- Versioning and tagging functionality remain intact.  
- `GitVersion.yml` is updated with the new format and validated against version 6 requirements.
